version: '3'

services:

  wakivote-db:
    image: postgres
    container_name: wakivote-db
    restart: always
    networks:
      - wakivote-nw
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=wakivote
    volumes:
      - pgdata:/data/postgres

  wakivote-app:
    build: .
    container_name: wakivote-app
    depends_on:
      - wakivote-db
    networks:
      - wakivote-nw
    environment:
      - DB_HOST=wakivote-db
      - LOG_LEVEL=DEBUG
    ports:
      - 8080:8080

volumes:
  pgdata:
    driver: local

networks:
  wakivote-nw:
    driver: bridge